application: drive-music-player
version: nov-2015
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: index.html
  upload: index.html

- url: /icon_128\.png
  static_files: cws/icon_128.png
  upload: cws/icon_128.png

- url: /images
  static_dir: images

- url: /cws
  static_dir: cws

- url: /js
  static_dir: js

- url: /third-party
  static_dir: third-party

- url: /css
  static_dir: css

- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json

- url: /manifest.webapp
  static_files: manifest.webapp
  upload: manifest.webapp
